server:
  port: 5000

spring:
  application:
    name: itbo-router-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/

zuul:
#  SendResponseFilter:
#    post:
#      disable: true  #禁用指定的filter
  ignored-services: '*'
  servlet-url: /
  prefix: /v1   #接口版本号，访问需要加上
  routes:
    sys:
      path: /sys/**
      serviceId: itbo-service-sys
    ribbon:
      path: /ribbon/**
      serviceId: eureka-ribbon-client
    feign:
      path: /feign/**
      serviceId: eureka-feign-client

