server:
  port: 5000

spring:
  application:
    name: itbo-router-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/

zuul:
  ignored-services: '*'
  servlet-url: /
  routes:
    sys:
      path: /sys/**
      serviceId: itbo-service-sys
    ribbon:
      path: /ribbon/**
      serviceId: eureka-ribbon-client
    feign:
      path: /feign/**
      serviceId: eureka-feign-client
