server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/

spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  application:
    name: itbo-service-sys
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tbo
    username: root
    password: 123456

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.chizuko.itbo.service.sys.entity
  mapperLocations: classpath:mapper/*.xml

