server:
  port: 8763

spring:
  application:
    name: eureka-server2

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/
